updated shell script to use words file

diff --git a/password b/password
--- a/password
+++ b/password
@@ -1,41 +1,59 @@
 #!/bin/bash
 
-charset=""
-length=8
+# Path to your compressed wordlist
+WORDLIST="./source/words.txt.gz"
 
-for arg in "$@"; do
-  case $arg in
-    -n) charset+="0-9" ;;
-    -a) charset+="a-z" ;;
-    -A) charset+="A-Z" ;;
-    -S) charset+="!@#$%^&*()_+=-{}[]:;<>,.?/" ;;
-    [0-9]*) length=$arg ;;
-  esac
-done
+# default word count
+WORDS=4
 
-if [ -z "$charset" ]; then
-  charset="a-zA-Z0-9!@#$%^&*()_+=-{}[]:;<>,.?/"
+# if user passed length argument
+if [[ "$1" =~ ^[0-9]+$ ]]; then
+  MAXLEN="$1"
+else
+  MAXLEN=0
 fi
 
-if [ "$length" -lt 5 ]; then
-  < /dev/urandom tr -dc "$charset" | head -c "$length"
-  echo
-  exit 0
+# Read and decompress the dictionary safely
+if [[ -f "$WORDLIST" ]]; then
+  wordlist=$(gzip -dc "$WORDLIST")
+else
+  echo "Error: $WORDLIST not found"
+  exit 1
 fi
 
-build_password() {
-  result=""
-  [[ "$charset" == *"a-z"* ]] && result+=$(< /dev/urandom tr -dc 'a-z' | head -c1)
-  [[ "$charset" == *"A-Z"* ]] && result+=$(< /dev/urandom tr -dc 'A-Z' | head -c1)
-  [[ "$charset" == *"0-9"* ]] && result+=$(< /dev/urandom tr -dc '0-9' | head -c1)
-  [[ "$charset" == *"!"* ]]   && result+=$(< /dev/urandom tr -dc '!@#$%^&*()_+=-{}[]:;<>,.?/' | head -c1)
-  restlen=$((length - ${#result}))
-  [[ $restlen -gt 0 ]] && result+=$(< /dev/urandom tr -dc "$charset" | head -c "$restlen")
+# Convert to array
+mapfile -t WORDS_ARRAY <<< "$wordlist"
 
-  echo "$result" | fold -w1 | shuf | tr -d '\n'
-  echo
+pick_word() {
+  printf "%s" "${WORDS_ARRAY[$RANDOM % ${#WORDS_ARRAY[@]}]}"
 }
 
-build_password
+pick_number() {
+  shuf -i 2-3333 -n 1
+}
 
-#command issue while generating mixtures
+generate() {
+  local pw=""
+  local count=$((RANDOM % 6 + 3))   # 3–8 segments like Python
+
+  for ((i=0;i<count;i++)); do
+    toss=$((RANDOM % 4))
+    if [[ $toss -eq 0 || $toss -eq 1 ]]; then
+      pw+=$(pick_word)
+    else
+      pw+=$(pick_number)
+    fi
+  done
+
+  echo "$pw"
+}
+
+# Generate raw password
+password=$(generate)
+
+# Trim to maximum length if needed
+if [[ $MAXLEN -gt 1 ]]; then
+  password="${password:0:MAXLEN}"
+fi
+
+echo "password: $password"
